### ISSUE TITLE
Failed to create publisher: publisher: unable to obtain EC2 service client error in cni-metrics helper

### ISSUE THREAD

**Issue by KR411-prog** [aws/amazon-vpc-cni-k8s#1274] opened 2020-10-31 04:10 UTC
I just followed the document https://docs.aws.amazon.com/eks/latest/userguide/cni-metrics-helper.html#install-metrics-helper

I have created the IAM policy as mentioned and added it to the node instance profile.
and deployed the manifests ,

kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.7/config/v1.7/cni-metrics-helper.yaml

However I am getting crashlooping pods ,
`cni-metrics-helper-86c497cf87-k2928   0/1     CrashLoopBackOff   4          3m27s`

Here is the error logs in the pod,
```
kubectl logs cni-metrics-helper-86c497cf87-k2928 -n kube-system
{"level":"info","ts":"2020-10-31T04:03:46.292Z","caller":"runtime/proc.go:203","msg":"Starting CNIMetricsHelper. Sending metrics to CloudWatch: true, LogLevel Debug"}
{"level":"fatal","ts":"2020-10-31T04:03:52.733Z","caller":"runtime/proc.go:203","msg":"Failed to create publisher: publisher: unable to obtain EC2 service client: EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: RequestError: send request failed\ncaused by: Get http://169.254.169.254/latest/dynamic/instance-identity/document: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
```

Any help on what I am missing here? I thought the document instructions would work.Is there any additional config needed?

**Comment by jayanthvn** [comment] 2020-10-31 05:39
Hi @KR411-prog 

I tried the steps in the document and applied the cni-metrics yaml and It is working on my cluster. Which AWS CNI version are you using? Do you have weave CNI enabled? Are you using any network policy like calico which blocks pod access to EC2 metadata? 

Thank you!

**Comment by KR411-prog** [comment] 2020-11-03 00:29
Hi @jayanthvn 

I have EKS cluster. and its using aws-node by default
```
kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2
amazon-k8s-cni:v1.6.3-eksbuild.1
```

**Comment by jayanthvn** [comment] 2020-11-03 00:52
Hi @KR411-prog 

Can you please try if the below `curl` works from aws-node pod? Just want to make sure the issue is only with cni-metrics-helper.

```
kubectl exec -it aws-node-9zsmx -n kube-system -- /bin/bash
```

```
curl http://169.254.169.254/latest/dynamic/instance-identity/document
```

Also if it is fine, kindly email me (varavaj@amazon.com) CNI logs [`sudo bash /opt/cni/bin/aws-cni-support.sh`] and cluster ARN.

Thank you!

**Comment by KR411-prog** [comment] 2020-11-03 04:16
Thankyou @jayanthvn 

Here are the details..
```

curl http://169.254.169.254/latest/meta-data/
ami-id
ami-launch-index
ami-manifest-path
block-device-mapping/
events/
hostname
iam/
identity-credentials/
instance-action
instance-id
instance-life-cycle
instance-type
local-hostname
local-ipv4
mac
metrics/
network/
placement/
profile
reservation-id
security-groups
services/

```
```
curl http://169.254.169.254/latest/dynamic/instance-identity/document
{
  "accountId" : "707057151399",
  "architecture" : "x86_64",
  "availabilityZone" : "us-east-1c",
  "billingProducts" : null,
  "devpayProductCodes" : null,
  "marketplaceProductCodes" : null,
  "imageId" : "ami-0ef76ba092ce4e253",
  "instanceId" : "i-0ffdc7558b56d9d78",
  "instanceType" : "m5.large",
  "kernelId" : null,
  "pendingTime" : "2020-11-02T16:58:42Z",
  "privateIp" : "10.73.32.73",
  "ramdiskId" : null,
  "region" : "us-east-1",
  "version" : "2017-09-30"
}

```
```
iptables -L -t nat | grep 169.254.169.254
bash-4.2# 
```
iptables command seems to return no output..
I have also sent you email on logs and arn

**Comment by jayanthvn** [comment] 2020-11-03 04:45
Hi @KR411-prog 

Thanks for checking, I have deleted the data since it contains account id and other information. Looks like only cni-metrics pod is not able to access ec2 metadata since the instance and the aws-node is able to access it. The o/p you shared is from the instance and aws-node right?

Thank you!

**Comment by KR411-prog** [comment] 2020-11-03 18:16
I have even tried IRSA by mapping Service account to the IAM policy but still ended up with same error,
`{"level":"fatal","ts":"2020-11-03T18:00:20.350Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"Failed to create publisher: publisher: unable to obtain EC2 service client: EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: RequestError: send request failed\ncaused by: Get http://169.254.169.254/latest/dynamic/instance-identity/document: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)","stacktrace":"github.com/aws/amazon-vpc-cni-k8s/pkg/utils/logger.(*structuredLogger).Fatalf\n\t/go/src/github.com/aws/amazon-vpc-cni-k8s/pkg/utils/logger/zaplogger.go:83\nmain.main\n\t/go/src/github.com/aws/amazon-vpc-cni-k8s/cmd/cni-metrics-helper/main.go:97\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}`

**Comment by KR411-prog** [comment] 2020-11-04 23:34
Looks like...we have hit this same issue https://github.com/aws/amazon-vpc-cni-k8s/issues/663

**Comment by jayanthvn** [comment] 2020-11-04 23:35
Hi @KR411-prog 

Yes we also suspect that is the issue. Nithish (@nithu0115) is working on a fix.

Thank you!

**Comment by KR411-prog** [comment] 2020-11-04 23:36
Can we know when we can expect the fix?

**Comment by KR411-prog** [comment] 2020-11-05 19:09
@jayanthvn  .. Our requirement is to use Prometheus and not Cloudwatch. So we found cni-metrics-helper not needed for us as its only helpful for cloudwatch.
I have created service and servicemonitor for aws-cni and that is working fine for Prometheus metrics.
Thankyou for the help anyways.

**Comment by jayanthvn** [comment] 2020-11-05 19:14
Thanks for letting us know @KR411-prog. But we will verify if this issues fixes with @nithu0115 changes. For now I will close this issue then.

**Closed by jayanthvn** 2020-11-05 19:14 UTC
Labels: needs investigation, question
