### ISSUE TITLE
amazon-vpc-cni-k8s issue to pull image

### ISSUE THREAD

**Issue by bhavasarpritesh** [aws/amazon-vpc-cni-k8s#2783] opened 2024-02-05 13:06 UTC
**What happened**:

I have updated k8s version to 1.29 and now getting error │   Warning  FailedCreatePodSandBox  4m38s (x255 over 59m)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "877085696533.dkr.ecr.af-south-1.amazonaw ││ s.com/eks/pause:3.1-eksbuild.1": failed to pull image "877085696533.dkr.ecr.af-south-1.amazonaws.com/eks/pause:3.1-eksbuild.1": failed to pull and unpack image "877085696533.dkr.ecr.af-south-1.amazonaws.com/ek ││ s/pause:3.1-eksbuild.1": failed to resolve reference "877085696533.dkr.ecr.af-south-1.amazonaws.com/eks/pause:3.1-eksbuild.1": pull access denied, repository does not exist or may require authorization: author ││ ization failed: no basic auth credentials
**Attach logs**

![Capture](https://github.com/aws/amazon-vpc-cni-k8s/assets/57290154/900d8f40-5dd7-4c94-82f5-aff08e9e943b)

**What you expected to happen**:
kubelet should be able to pull image

**Environment**:
- Kubernetes version (use `kubectl version`):1.29 
- CNI Version - v1.16.2

**Comment by jdn5126** [comment] 2024-02-05 16:00
@bhavasarpritesh this is an AMI issue, not an issue with the AWS VPC CNI. This is a duplicate of https://github.com/aws/amazon-vpc-cni-k8s/issues/2778, where the root cause is the garbage collector deleting the pause image, which is discussed in https://github.com/awslabs/amazon-eks-ami/issues/1597.

This is fixed in the latest EKS AMI release: https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240202

**Closed by jdn5126** 2024-02-05 16:00 UTC
Labels: bug
