### ISSUE TITLE
cni version 1.7.6. Pods are failing to launch.

### ISSUE THREAD

**Issue by Arsen-Uulu** [aws/amazon-vpc-cni-k8s#1322] opened 2020-12-10 17:40 UTC
**What happened**:
Pods Failing to launch in my cluster. All pods are in  `ContainerCreating` state
 Include log lines if possible
 -->

**Attach logs**
Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "9742b380336c57443151508a577ace541c2b6c44b278f73f9afc7a2c23053220" network for pod "cluster-autoscaler-7f8f7cdb4d-64lt4": networkPlugin cni failed to set up pod "cluster-autoscaler-7f8f7cdb4d-64lt4_kube-system" network: add cmd: Error received from AddNetwork gRPC call: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:50051: connect: connection refused", failed to clean up sandbox container "9742b380336c57443151508a577ace541c2b6c44b278f73f9afc7a2c23053220" network for pod "cluster-autoscaler-7f8f7cdb4d-64lt4": networkPlugin cni failed to teardown pod "cluster-autoscaler-7f8f7cdb4d-64lt4_kube-system" network: del cmd: error received from DelNetwork gRPC call: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:50051: connect: connection refused"]

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17
- CNI Version: 1.7.6
- OS (e.g: `cat /etc/os-release`): NAME="Amazon Linux" VERSION="2"
- Kernel (e.g. `uname -a`): 4.14.186-146.268.amzn2.x86_64

**Comment by jayanthvn** [comment] 2020-12-10 18:01
Hi @Arsen-Uulu 

Can you please share me the logs after running this script on the node - `sudo bash /opt/cni/bin/aws-cni-support.sh`. Also please share the o/p of aws-node DaemonSet.

Is this with custom networking or have you enabled security group per pod? 

Thanks.

**Comment by SaranBalaji90** [comment] 2020-12-10 18:45
@jayanthvn Synced up with @Arsen-Uulu offline. Looks like they are not using Customer networking/per pod feature.

Error message in their log
```
{"level":"error","ts":"2020-12-10T17:09:31.682Z","caller":"aws-k8s-agent/main.go:28","msg":"Initialization failure: open /var/run/aws-node/ipam.json.tmp156063755: no such file ordirectory"}
{"level":"error","ts":"2020-12-10T17:23:28.745Z","caller":"aws-k8s-agent/main.go:28","msg":"Initialization failure: open /var/run/aws-node/ipam.json.tmp135855914: no such file ordirectory"}
```

Asked @Arsen-Uulu to run `kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.7/aws-k8s-cni.yaml` to see if this mitigates the issue.

**Comment by jicowan** [comment] 2020-12-14 01:45
@SaranBalaji90 I am also having this issue.  Using 1.7.7 on 1.18 (managed nodes).  The only way I could get the CNI to stop restarting was to remove the liveness and readiness probes, but that doesn't resolve the underlying issue.  The CNI is failing to respond on port 50051.

**Comment by SaranBalaji90** [comment] 2020-12-14 02:49
Looks like @jicowan doesn't have managed ng now on the affected cluster. Once he spins up new NG tomorrow, we can investigate why CNI is timing out on his cluster.

**Comment by jicowan** [comment] 2020-12-16 19:49
I created a new cluster [1.18] and upgraded the CNI to 1.7.7 and it worked.  I can't explain why the probes failed or why they would only work on self-managed workers. Perhaps iptables got corrupted on my managed nodes.

**Comment by abhipth** [comment] 2020-12-16 19:54
I also tried to reproduce the issue with v1.18 cluster and with cni v1.7.7 on a managed node group and it is working as expected.

**Comment by abhipth** [comment] 2020-12-16 20:19
I tested both v1.7.7 and v1.7.6 and was not able to reproduce the issue.

I did encountered Liveness probe failed when I deleted my managed add on and applied the cni v1.7.7 manually. It was because the worker role ARN didn't have AmazonEKS_CNI_Policy attached. After attaching the policy everything worked as expected. 

I am not sure if @jicowan and @Arsen-Uulu ran into similar issues but since they have deleted the clusters we will not be able to investigate the root cause. 

Synced up with @SaranBalaji90 and closing the issue given everything is working as expected for both. Please re open if you run into this again.

**Closed** 2020-12-16 20:20 UTC
Labels: bug

**Comment by jicowan** [comment] 2020-12-17 01:03
I am able to reproduce now.  Create a cluster with a managed node group.  Add the VPC CNI as a managed add on.  The aws-node will start failing the probes.

**Comment by abhipth** [comment] 2020-12-17 18:17
Thanks for reporting @jicowan, tracking this issue here - https://github.com/aws/amazon-vpc-cni-k8s/issues/1338

**Comment by Arsen-Uulu** [comment] 2020-12-17 18:21
@abhipth  I have fixed my issue.

What I did is I updated cni plugin version directly on an existing EKS Cluster, but after applying `https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.7/aws-k8s-cni.yaml` issue was resolved.

**Comment by sarbajitdutta** [comment] 2021-07-26 18:34
I have similar issue Readiness probe is failing for one of the pods - I removed the readiess probe from manifest - 
```
readinessProbe:
            exec:
              command:
                - /app/grpc-health-probe
                - '-addr=:50051'
            initialDelaySeconds: 1
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
```

**Comment by jayanthvn** [comment] 2021-07-26 19:17
Hi @sarbajitdutta 

Wanted to understand more on this, so you scaled up the nodes and one of the `aws-node` pod is failing? Is possible to email me (varavaj@amazon.com) the ipamd logs from that node?

**Comment by sarbajitdutta** [comment] 2021-07-29 17:03
@jayanthvn When I did an instance refresh the error went away. I will send you the logs if the issue props up again.

The cluster autoscaler was causing problems due to OOM.
