### ISSUE TITLE
curl do not pass through when both source node and target node are same

### ISSUE THREAD

**Issue by ravicm** [aws/amazon-vpc-cni-k8s#840] opened 2020-02-12 15:23 UTC
Steps to reproduce the issue:

1. Create an eks cluster (Killer-eks in our case) with secondary IP support.
2. Create an autoscaling group of one node and attach to the cluster.
3. Create a network load balancer, listeners, target groups. 
4. Create a hosted zone in Route 53. Add a recordset of type cname mapped to the loadbalancer.
5. Deploy nginx ingress controller in the cluster of nodeport type.
6. All the above are connected as NLB -> listeners -> Target groups -> autoscaling group nodes
7. Deploy a simple nginx deployment(my-nginx) in the cluster, map it to the nginx service(my-nginx) and to the ingress (my-nginx-ingress).
8. Deploy another simple nginx pod (my-nginx1) in the cluster.
9. Enter into one of the pods say my-nginx1
10. curl the ingress endpoints. curl fails

Slightly different environment is set up in my case and the test cases are demonstrated in the attached file in detail.
[eks-nlb-issue-aws-support.txt](https://github.com/aws/amazon-vpc-cni-k8s/files/4193108/eks-nlb-issue-aws-support.txt)

**Comment by paurosello** [comment] 2020-03-15 11:07
We are facing the same issue, did you find a solution?

**Comment by jonathan-mothership** [comment] 2020-04-09 20:57
I'm facing the same issue!
CNI v1.6.0
We have a different ingress controller (Traefik) and are seeing the same issue. In a 3-node ASG, a pod on node A that makes a request to an NLB where that request is served by same backend node running the requesting pod, the connection times out. We have two listeners and this happens on both the TLS and TCP listeners. 

My suspicion is that this is because the NLB preserves the source IP of the request when connecting to the backend and the CNI iptables rules are getting tripped up with that connection.

**Comment by bhaveshph** [comment] 2020-07-13 19:26
I am seeing this issue too.

But when I call from outside cluster node, it works fine
I guess, if I am on same eks cluster, I would use k8s-svc and not NLB; I guess I am fine for now; but interested to see what how it is happening.

**Comment by achevuru** [comment] 2020-09-02 06:22
@ravicm @jonathan-mothership 

 Expected behavior with NLB when both Source and Target Nodes are same. Internal NLB do not support loopback or hair pinning. Since NLB in instance mode preserves the source ip of the packet, the response (say SYN ACK) will directly go to the local client pod. So, SYN will have client PodIP as SIP and NLB IP as DIP where as SYN ACK will have server PodIP as SIP(and not NLB IP) and client PodIP as DIP when both the pods are on the same node, so client pod will terminate/reset the TCP session. 

Refer to “Connections time out for requests from a target to its load balancer” section in the below guide. It also lists out possible options. NLB in IP mode should help out in this scenario.

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-troubleshooting.html.

**Comment by jayanthvn** [comment] 2020-11-04 19:23
Hi,

Since this is an expected behavior will be closing this issue for now.

Thank you!

**Closed by jayanthvn** 2020-11-04 19:23 UTC
Labels: documentation
