### ISSUE TITLE
 liveness/readiness  probe keep failing after AMI upgade to 1.25.6-20230217

### ISSUE THREAD

**Issue by lz000** [aws/amazon-vpc-cni-k8s#2300] opened 2023-03-02 04:10 UTC
**What happened**:
I'm upgrading the node group to 1.25.6-20230217 on EKS. Before this, I already upgraded the kubernetes version to v1.25. I also updated the amazon-k8s-cni to v1.12.5 using  `kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.12.5/config/master/aws-k8s-cni.yaml`. Now the `aws-node` pods keep failing on liveness probe. Here is the error

```
Liveness probe failed: {"level":"info","ts":"2023-03-02T03:30:32.431Z","caller":"/root/sdk/go1.19.2/src/runtime/proc.go:250","msg":"timeout: failed to connect service \":50051\" within 5s"}
```

I checked the pod logs, found nothing useful.

`aws-node`:
```
Installed /host/opt/cni/bin/aws-cni
Installed /host/opt/cni/bin/egress-v4-cni
time="2023-03-02T03:49:09Z" level=info msg="Starting IPAM daemon... "
time="2023-03-02T03:49:09Z" level=info msg="Checking for IPAM connectivity... "
time="2023-03-02T03:49:10Z" level=info msg="Copying config file... "
time="2023-03-02T03:49:10Z" level=info msg="Successfully copied CNI plugin binary and config file."
```

`aws-vpc-cni-init`
```
time="2023-03-02T02:21:57Z" level=info msg="Copying CNI plugin binaries ..."
Installed /host/opt/cni/bin/loopback
Installed /host/opt/cni/bin/portmap
Installed /host/opt/cni/bin/bandwidth
Installed /host/opt/cni/bin/host-local
time="2023-03-02T02:21:57Z" level=info msg="Copied all CNI plugin binaries to /host/opt/cni/bin"
Installed /host/opt/cni/bin/aws-cni-support.sh
time="2023-03-02T02:21:57Z" level=info msg="Found primaryMAC 06:f9:e3:85:70:58"
time="2023-03-02T02:21:57Z" level=info msg="Found primaryIF eth0"
time="2023-03-02T02:21:57Z" level=info msg="Updated net/ipv4/conf/eth0/rp_filter to 2\n"
time="2023-03-02T02:21:57Z" level=info msg="Updated net/ipv4/tcp_early_demux to 1\n"
time="2023-03-02T02:21:57Z" level=info msg="CNI init container done"
```

I already looked at https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/troubleshooting.md#known-issues, and tried increasing the liveness/readiness probe timeout to 20s but still no avail. I have another node group running on AMI version 1.24.10-20230217, and the same aws-node works fine.

Please advice how this can be resolved

**Environment**:
- Kubernetes version (use `kubectl version`): 1.25
- CNI Version: 1.12.5
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by lz000** [comment] 2023-03-02 16:31
Yes, it runs fine on 1.24 AMI. Where do I run `aws-cni-support.sh`? on the machine where I run the `kubectl apply` or inside the aws-node pod container? same for the `/var/log/aws-routed-eni/ipamd.log`, where do I find this file?

**Comment by jdn5126** [comment] 2023-03-02 16:33
> Yes, it runs fine on 1.24 AMI. Where do I run `aws-cni-support.sh`? on the machine where I run the `kubectl apply` or inside the aws-node pod container? same for the `/var/log/aws-routed-eni/ipamd.log`, where do I find this file?

These filesystem paths are on the node, so you would need to run from a session on any of the nodes where aws-node pod is failing probe.

**Comment by jdn5126** [comment] 2023-03-02 18:33
We coordinated through k8s Slack and resolved the API server connectivity issue to an outdated kube-proxy version. Closing this issue as there are no pending items from VPC CNI.

**Closed by jdn5126** 2023-03-02 18:33 UTC
Labels: question, needs investigation

**Comment by michaljrk** [comment] 2023-03-06 11:49
Could you share more details about the resolution @jdn5126 ? Isn't `kuby-proxy` managed by EKS itself? How can I update manually (or confirm my issue is caused by the same)?
I've encountered the same issue as described above after upgrading to v1.25 (I tried on both managed node versions - AMI 1.24 and 1.25, and the outcome is the same).

Thank you.

**Comment by jdn5126** [comment] 2023-03-06 16:33
@michaljrk `kube-proxy` is installed by default on EKS cluster creation, but updating the addon is a manual process. The recommendation from upstream k8s is that the `kube-proxy` version match the k8s version, and the minimum not skew by more than 2 major versions. So if you have EKS 1.25, the recommended kube-proxy version is `v1.25.6-minimal-eksbuild.1`, while the minimum supported is 1.23+. You can check the kube-proxy version with:
```
kubectl describe ds kube-proxy -n kube-system | grep -i image
```

For EKS to take more ownership of addons, we recommend installing the managed addon: https://docs.aws.amazon.com/eks/latest/userguide/managing-add-ons.html

To update the kube-proxy version without using the managed addon service, you can follow https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html

**Comment by jdn5126** [comment] 2023-03-06 16:34
@michaljrk note that the same logic applies for `coredns`: https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html

**Comment by michaljrk** [comment] 2023-03-06 23:09
I can confirm it's working now after upgrading both - `kube-proxy` and `cordens` to the recommended versions. Thank you for your help @jdn5126 .
It would be great if that step wast mentioned in the EKS cluster upgrade documentation on AWS (even though managed addons are the recommended, I think quite a few users might encounter the same issue when upgrading to v1.25, because `kube-proxy` and `coredns` are by default installed as self-managed when using tools like `terraform` (according to AWS docs, only when using web console or `eksctl` with config file, the addons are installed as managed).

**Comment by jdn5126** [comment] 2023-03-06 23:11
@michaljrk yeah, I would agree. Which document are you referring to? I can work on getting that updated

**Comment by michaljrk** [comment] 2023-03-06 23:17
> @michaljrk yeah, I would agree. Which document are you referring to? I can work on getting that updated

I would say here somewhere (in the `Kubernetes 1.25` section):
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

**Comment by jdn5126** [comment] 2023-03-09 19:32
@michaljrk Just looked and step 8 in https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html does call out to update the cluster addon versions as well, and mentions `kube-proxy`
