### ISSUE TITLE
cni-metrics-helper continues accessing a node after it's gone

### ISSUE THREAD

**Issue by tdmalone** [aws/amazon-vpc-cni-k8s#592] opened 2019-08-21 01:04 UTC
Hi there,

After terminating a node, it appears that `cni-metrics-helper` is still trying to access the no-longer-existing `aws-node` pod:

```
E0821 01:02:31.304392       1 cni_metrics.go:144] grabMetricsFromTarget: Failed to grab CNI endpoint: the server could not find the requested resource (get pods aws-node-ngnhh:61678)
E0821 01:01:31.303667       1 metrics.go:406] Failed to getMetricsFromTarget: the server could not find the requested resource (get pods aws-node-ngnhh:61678)
```

The above messages are logged every 30 seconds after node termination, until the `cni-metrics-helper` pod is restarted.

**Comment by Zyqsempai** [comment] 2019-10-02 07:42
I will take this one!

**Comment by shyamjvs** [comment] 2019-10-04 19:22
This is expected behaviour and I'm not sure if there is anything to fix here. You can see the following code:

https://github.com/aws/amazon-vpc-cni-k8s/blob/ccf1c29e451cf2bebc3e490b83db05245a14cc27/cni-metrics-helper/metrics/metrics.go#L404-L409

If an underlying cloud instance is deleted, it takes a while for the node to become unready (because kubelet stops posting heartbeats) and node-controller eventually deletes the node when it checks that the underlying instance has been deleted in the cloud-provider. Soon after, the pod is also deleted by k8s pod_gc_controller which sees that the pod is orphaned (i.e running on a non-existing node). All of this can take around 60-90 sec from the point where the instance was deleted. So any attempts to fetch metrics from the pod in the meanwhile *will* fail, which is why we simply log the error and continue with other pods inside the above code.

**Comment by shyamjvs** [comment] 2019-10-04 19:24
Let me know if there's still some issue I'm missing. Or we can close it.

**Comment by tdmalone** [comment] 2019-10-05 04:15
I get this log message turning up for much longer than 60-90 seconds after termination - possibly over half an hour or more, but I'll need to test to verify that. My assumption was that, currently, it would keep happening forever (until I restart the `cni-metrics-helper` pod).

I only noticed it because I have a log alert tracking words like 'failed' to pick up on issues I might not've noticed otherwise. I can easily exclude this particular event from that alert and then the problem essentially 'goes away' - but it seemed to me like something was wrong if this keeps happening for a long time.

**Comment by jaypipes** [comment] 2019-11-06 18:25
@tdmalone ping on this. have you continued to see the behaviour over long(er than 60-90s) periods?

**Comment by jaypipes** [comment] 2019-11-06 18:50
@tdmalone what do you think about us just either rewording the "error" message involved here to remove the wording "failed", since this behaviour is expected when a node is terminated? I think long-term, we want to get rid of the metrics helper entirely and use an exporter strategy to the upstream metrics server, so we don't want to make big changes to this at this time.

**Comment by mogren** [comment] 2020-01-29 19:00
I agree that this should be at Warning log level instead of Error. Ping @nithu0115

**Comment by nithu0115** [comment] 2020-01-30 00:49
I agree, noted, I will change this to warning instead of error.

**Closed** 2020-05-20 18:04 UTC
Labels: needs investigation
