### ISSUE TITLE
Error configuring eth0 RPF check on CentOS 7.5

### ISSUE THREAD

**Issue by ewbankkit** [aws/amazon-vpc-cni-k8s#190] opened 2018-10-01 15:42 UTC
VPC CNI v1.2.0 running on CentOS Linux release 7.5.1804, IPAMD fails to start:

```
2018-10-01T15:11:02Z [INFO] Setting up host network
2018-10-01T15:11:02Z [ERROR] Failed to setup host networkfailed to configure eth0 RPF check: open /proc/sys/net/ipv4/conf/eth0/rp_filter: no such file or directory
2018-10-01T15:11:02Z [ERROR] initialization failureipamd init: failed to setup host network: failed to configure eth0 RPF check: open /proc/sys/net/ipv4/conf/eth0/rp_filter: no such file or directory
```

**Comment by ewbankkit** [comment] 2018-10-01 15:45
As this code is conditional on NodePort support being enabled, setting

```yaml
env:
  - name: AWS_VPC_CNI_NODE_PORT_SUPPORT
    value: "false"
```

allows the CNI to start but of course you get no NodePort support.

**Comment by ewbankkit** [comment] 2018-10-01 16:07
CentOS 7 doesn't have `eth0` 😄:
* https://wiki.centos.org/FAQ/CentOS7#head-62d45421abea0220e3038796e3dd5315906fa493

**Comment by liwenwu-amazon** [comment] 2018-10-03 20:08
This is a duplicate of #171  and will track the progress over there.  Thanks

**Closed by liwenwu-amazon** 2018-10-03 20:08 UTC
