### ISSUE TITLE
Workaround with packet dropped and retransmission

### ISSUE THREAD

**Issue by rubenlohaus** [aws/amazon-vpc-cni-k8s#516] opened 2019-06-26 19:06 UTC
The Linux Kernel has a known race condition when doing source network address translation (SNAT) that can lead to SYN packets being dropped. DNAT are affected too.

Amzn2 aws-node image provided by default to use as AWS VPC CNI have an outdated iptables version (iptables v1.4.21), and CNI plugin have the option to use --random-fully via AWS_VPC_K8S_CNI_RANDOMIZESNAT environment variable, but is only compatible with iptables >=1.6.2.

We are working on an old k8s migration to EKS and we are trying to make this works.

Any workaround or suggestions??

More detailed info about the issue:
https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02

**Comment by cidrick** [comment] 2019-07-26 16:00
I've run into this same issue where we're seeing SYN packets being dropped while `AWS_VPC_K8S_CNI_EXTERNALSNAT` is set to `false`. I've been testing potential workarounds, and the only one that seems to work so far is to change `AWS_VPC_K8S_CNI_EXTERNALSNAT` to `true` so that our NAT gateways perform SNAT, we can't use this in production due to how we have our VPC peering set up with some of our neighbors. 

It'd be great if anyone could chime in with suggestions or a timeline on a fix.

**Comment by jaypipes** [comment] 2019-12-11 19:19
The root cause of this is old kernel/packages in the EKS AMI. We have created an issue in the EKS AMI repo for tracking.

https://github.com/awslabs/amazon-eks-ami/issues/380

Closing this as duplicate (not related to AWS VPC plugin)

**Closed by jaypipes** 2019-12-11 19:19 UTC
Labels: bug, needs investigation
