### ISSUE TITLE
aws-node health check failing because loopback interface is down

### ISSUE THREAD

**Issue by abhipth** [aws/amazon-vpc-cni-k8s#1360] opened 2021-01-27 05:04 UTC
**What happened**:
IPAMD health check probes are failing because loop back interface is down.

Pod Event
```
Warning Unhealthy 5m49s (x463 over 144m) kubelet, <NODE-NAME> (combined from similar events): Readiness probe failed: {"level":"info","ts":"2021-01-15T17:34:47.458Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"timeout: failed to connect service ":50051" within 1s"}
```
Error Log
```
{"level":"error","ts":"2021-01-15T11:53:29.769Z","caller":"routed-eni-cni-plugin/cni.go:249","msg":"Error received from DelNetwork gRPC call for container CONTAINER  rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:50051: i/o timeout\""}
```

**Check if you are running into the issue**:

You can verify if you are running into this issue by running `ifconfig -a` if you see loopback interface is listed **without** UP/RUNNING then you are likely hitting this issue.
```
lo: flags=8<LOOPBACK>  mtu 65536
```
If your loopback is UP and Running then you are not running into this issue
```
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
```

**What could lead to the issue**
Currently we have observed the following conditions can lead to this issue.
- Kubelet crashing multiple times.
- Node under memory pressure.
- Disk operations are failing.

We are still working on finding the root cause but users can follow the below workarounds to mitigate the issue.

**Mitigation Steps**
Bring up the loopback interface
  ```
  sudo ip link set dev lo up
  ```
**or** Reboot the node
```
sudo reboot
``` 

We will update the ticket once we have found the exact root cause and reproduction steps.

**Comment by b225ccc** [comment] 2021-03-08 18:32
This just happened to me again.  The worker node is the same flavor as described in https://github.com/aws/amazon-vpc-cni-k8s/issues/1394.

I have the support bundle if it's helpful to anyone.

**Comment by jayanthvn** [comment] 2021-03-08 19:00
Hi @b225ccc 

Yes please share it with me - varavaj@amazon.com.

Thanks.

**Comment by shubydo** [comment] 2021-06-11 19:26
We are seeing the same error. Was there any resolution on this?

**Comment by b225ccc** [comment] 2021-07-08 15:50
> We are seeing the same error. Was there any resolution on this?

@shubydo we had this happen several times, but we were never able to find the root cause.  Our systems were experiencing high CPU load at the time these incidents were occurring.  We have that under better control now and we have not seen a reoccurrence of this issue.

**Comment by SachinKSingh28** [comment] 2021-07-13 14:52
I have the similar problem where loopback interface goes down on nodes occasionally and the build agent provisioned on this particular node times out connecting to kube proxy on the node on loopback interface. Only after bringing up the loopback interface, the build agents start to work again.

I have not been able to find any resource utilisation issues on the nodes when loopback interface goes down but we have prometheus installed on the cluster which suggests that node was unreachable for some time before it was marked as NotReady and after few minutes it becomes ready again. Any build agents scheduled on this node after this point start to fail trying to connect to kube proxy unless loop back is started.

Please share if you have found the actual problem or any solution.

**Comment by jayanthvn** [comment] 2021-08-30 18:20
We suspect the issue might be because of https://github.com/kubernetes/kubernetes/issues/100648. The root cause seems to be cri-o passing reused namespace on network teardown tricking the host network CNI DEL command into bringing down the `lo` or because of high memory pressure on this node possibly contributing to loopback interface going down. Once loopback interface goes down, aws-node (CNI pod) health check will fail causing it to be restarted.

upstream issue: https://github.com/cri-o/cri-o/issues/2849.

We are trying to repro locally to confirm this theory.

**Comment by yongzhang** [comment] 2021-09-20 12:16
same issue. is this addressed or not?

**Comment by jayanthvn** [comment] 2021-09-20 16:56
Upstream issue - https://github.com/containerd/containerd/issues/5630 is still open.

**Comment by hemalgadhiya** [comment] 2022-02-11 14:51
Any updates on this?

**Comment by dogzzdogzz** [comment] 2022-02-23 11:02
We are experiencing same issue after we introduced KEDA and use jobs to frequently create and terminate many short-live pods to consume SQS msgs

**Comment by jayanthvn** [comment] 2022-04-18 18:01
aws-node will not cause Lo to go down. Closing this issue. There are few upstream issues which can be tracked - https://github.com/containerd/containerd/issues/5630 and https://github.com/cri-o/cri-o/issues/2849. Good article on a similar issue - https://www.caseyc.net/home/localhost-special-1/

**Closed by jayanthvn** 2022-04-18 18:01 UTC
Labels: bug
