### ISSUE TITLE
Set preStop hook to prevent failures during node shutdown

### ISSUE THREAD

**Issue by grosser** [aws/amazon-vpc-cni-k8s#1556] opened 2021-07-27 02:11 UTC
example errors:
```
Failed killing the pod "foo": failed to "KillPodSandbox" for "bar" with KillPodSandboxError: "rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod \"foo\" network: del cmd: error received from DelNetwork gRPC call: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:50051: connect: connection refused\""
```

happen because cni shuts down quickly while other pods are still doing things on the node that is shutting down

we set
```
terminationGracePeriodSeconds: 190
```
and 
```
        lifecycle:
          preStop:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - echo 'preStop called, exiting in 180 seconds...'; sleep 180
```
to fix these, but ideally that would be upstream (or at lest documented somewhere) or we'd find some other solution for this

**Comment by jayanthvn** [comment] 2021-07-27 04:59
Hi @grosser 

Just trying to understand the use case here, Is there any reason you would want the aws-node pod to wait for all the pods to finish their tasks? ENIs and associated IPs will be released even if the aws-node pod is deleted since the node is getting terminated and the ENIs are marked as delete on termination.

**Comment by grosser** [comment] 2021-07-27 16:49
The problem was that we saw lots of errors in logs from cni being deleted before everything else got deleted.
All pods will die eventually, but ideally they'd do so without triggering errors which then spam our logs / trigger our alerting / might cause real issues in the pods still hanging around.

**Comment by haouc** [comment] 2021-07-27 18:35
Hey @grosser, would you mind to share more information how you terminate the nodes? By knowing exactly how you encountered this issue, we can try to reproduce on our side. Thanks.

**Comment by grosser** [comment] 2021-07-27 19:40
we drain them as we get the autoscale-down signal (leaving daemonset pods behind) and then let aws run shutdown
I assume the issue is that the remaining daemonset pods or whatever is still on there after the drain timeout causes the issue

**Comment by haouc** [comment] 2021-08-03 22:44
Hey @grosser, do you have any flag added when drain nodes? Such as `--ignore-daemonsets` or `--force` (https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#drain).

Also you mentioned 
> `leaving daemonset pods behind`
Do you mean the failing pod ("foo") is daemonset managed? We are expecting daemonset managed pods being reserved till nodes are terminated. Thanks.

**Comment by grosser** [comment] 2021-08-03 22:50
yes, we use `--ignore-daemonsets` and `--force` to drain the nodes, the issue comes when aws does the node-shutdown though and there we don't control the draining / kubelet & docker just get stopped by systemd

**Comment by haouc** [comment] 2021-11-09 22:47
@grosser thanks for all information. Since this is not generally applicable, I don't think we can add this hook into the VPC CNI manifest at this moment. Please feel free to let us know if you think otherwise.
I am closing this ticket for now. If you still have concern, please feel free to re-open it. Thanks.

**Closed by haouc** 2021-11-09 22:47 UTC
Labels: bug
