### ISSUE TITLE
helm chart install for aws-calico not working

### ISSUE THREAD

**Issue by johnthedev97** [aws/amazon-vpc-cni-k8s#1525] opened 2021-07-01 19:40 UTC
**What happened**:
I was following the instructions [here](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico to install) to install Calico on EKS. But it gives me the following error in second step

```
kubectl apply -k github.com/aws/eks-charts/tree/master/stable/aws-calico/crds                                                                            ─╯

error: evalsymlink failure on '/private/var/folders/kb/m99837vn047cc073_x3ctzg00000gp/T/kustomize-182158710/tree/master/stable/aws-calico/crds' : lstat /private/var/folders/kb/m99837vn047cc073_x3ctzg00000gp/T/kustomize-182158710/tree: no such file or directory
```

**Attach logs**

I feel this is a client side issue and not sure if there are any other relevant logs. I am running the commands from MAc.

**What you expected to happen**:

I expected the command to create the crds and finish without errors

**How to reproduce it (as minimally and precisely as possible)**:

These are the steps I executed

```
bash-5.1$ helm repo add eks https://aws.github.io/eks-charts
"eks" has been added to your repositories
bash-5.1$ kubectl apply -k github.com/aws/eks-charts/tree/master/stable/aws-calico/crds
error: evalsymlink failure on '/private/var/folders/kb/m99837vn047cc073_x3ctzg00000gp/T/kustomize-104579271/tree/master/stable/aws-calico/crds' : lstat /private/var/folders/kb/m99837vn047cc073_x3ctzg00000gp/T/kustomize-104579271/tree: no such file or directory
```

**Anything else we need to know?**:

**Environment**: EKS 1.20
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:40:09Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
- CNI Version 1.7.10
- OS (e.g: `cat /etc/os-release`): MacOS Big Sur
- Kernel (e.g. `uname -a`):

**Comment by jayanthvn** [comment] 2021-07-13 18:21
Hi @johnthedev97 

Can you please share kustomize version? This might be related to https://github.com/kubernetes-sigs/kustomize/issues/2538

**Comment by johnthedev97** [comment] 2021-07-19 10:05
Hi @jayanthvn 

I couldn't figure how to find it, but here it is the kubectl version details
```
 kubectl version --client                                                                                                                ─╯
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:40:09Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by achevuru** [comment] 2021-07-20 18:25
@johnthedev97 We were able to reproduce it as well. We will look in to it and provide an update.

**Comment by amitkatyal** [comment] 2021-08-01 16:29
https://github.com/aws/eks-charts/issues/315

**Comment by jayanthvn** [comment] 2021-10-03 05:54
@haouc recently made few fixes and also for another issue we did try helm install from https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico which is synced to eks-charts and it works - https://github.com/aws/amazon-vpc-cni-k8s/issues/1627#issuecomment-923255948. Can you please retry?

**Comment by haouc** [comment] 2022-02-10 22:46
@johnthedev97 @amitkatyal 
Since we are deprecating Calico charts in this repo, we recommend you to check our [important announcement](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico) and suggested [installation instruction](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) for required or latest Calico version. You can also refer to [Calico configuration reference](https://projectcalico.docs.tigera.io/reference/installation/api).
I am closing this ticket due to unsupported charts upgrade. Please feel free to send questions to our triage email (k8s-awscni-triage@amazon.com).

**Closed by haouc** 2022-02-10 22:46 UTC
Labels: bug, good first issue, calico
