### ISSUE TITLE
Pods hanging  due to IP address assignment issue while using Spot Instance

### ISSUE THREAD

**Issue by phlukman** [aws/amazon-vpc-cni-k8s#488] opened 2019-05-29 16:41 UTC
Hello all, we're running a EKS cluster with a couple of Spot instances and CNI plugin version is 1.4.1.
We have noticed that every time one of the spot instances gets replaced by a new one, one of the required pods is not able to start up due to IP address assignment issue. I noticed that there's  a similar issue 
already signaled ( https://github.com/aws/amazon-vpc-cni-k8s/issues/59 ) but I'm not sure it's related or is it?
thank you in advance
Patria

**Comment by phlukman** [comment] 2019-05-30 21:47
@mogren thanks for your time to look into this issue, let me know if you need any more info?
at this time we have replaced the spot instances by dedicated instances.

**Comment by bkruger99** [comment] 2019-06-27 21:11
I have a similar issue with eks 1.13 and aws cni 1.4.1...  I have a snapshot of logs if it'll help with investigation.  In our case the nodes to work after a bit settles, but a cronjob that it supposed to spin up just sits in limbo.  I'm looking through the logs and it recognizes there's a pod there, but it doesn't assign the ip.

**Comment by left4taco** [comment] 2019-07-02 21:01
We are also using spot-instances, and can sometimes see pod stuck at `ContainerCreating` stage. I believe this is because of the reason described in #59

**Comment by xrl** [comment] 2019-07-10 02:58
I see this as well in my spot instance setup. I'm not sure if it has to do with the spot instance or the fact that spot instance arrive due to excess pending pods (I have the kube cluster autoscaler). All those pods then rush on to the node as soon as it is marked "healthy". Perhaps the node isn't really healthy because the VPC CNI isn't done setting up the EC2 instance's network?

**Comment by left4taco** [comment] 2019-07-10 03:01
@xrl
Could you please check the ipamd output as I did above? Look for the sequence of pod being created and 30 up address being allocated. If you saw similar output as I did, then it might be the reason.

**Comment by schumacher-m** [comment] 2019-07-24 12:29
Also want to subscribe to this issue:

We're running: 
EKS 1.12
NAT Gateway VPC (Nodes are in a Private Subnet)
ASG with Spot and On-Demand Instances
CNI 1.5.0

Facing this issue now from time to time when we spawn Pods (on Spot Instances)

**Comment by schumacher-m** [comment] 2019-07-25 08:54
![image](https://user-images.githubusercontent.com/275356/61860233-e9761400-aec9-11e9-98d8-323c6bdecdca.png)

FYI: I've used `WARM_IP_TARGET` to set a fixed amount of IPs kept available. In our usecase we do have a spike (of pod schedules) in the morning to do data processing. I see a significant reduction after the change.

**Comment by schumacher-m** [comment] 2019-07-27 09:21
We encountered a smaller error spike now after we have accumulated a lot of Completed/Failed Pods. I have now cleaned up the completed/failed Pods and will check if that will result in again no error spike for one or two days.

**Comment by jaypipes** [comment] 2019-12-11 19:22
This was fixed in 1.5.3. The root cause was a race condition where kubelet considered the VPC CNI plugin as "ready" before the IPAMd service was fully up and running.

**Closed by jaypipes** 2019-12-11 19:22 UTC
Labels: needs investigation
